apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: social-network
  labels:
    app: jaeger-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
        - name: jaeger-query
          image: jaegertracing/jaeger-query
          args:
            - "--cassandra.keyspace=jaeger_v1_dc1"
            - "--cassandra.servers=cassandra"
          ports:
            - containerPort: 16686
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: social-network
spec:
  selector:
    app: jaeger-query
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
  type: ClusterIP