apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: social-network
  labels:
    app: jaeger-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
    spec:
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector
          args:
            - "--cassandra.keyspace=jaeger_v1_dc1"
            - "--cassandra.servers=cassandra"
            - "--collector.zipkin.host-port=9411"
            - "--collector.num-workers=100"
            - "--collector.queue-size=100000"
          ports:
            - containerPort: 14269
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: social-network
spec:
  selector:
    app: jaeger-collector
  ports:
    - name: grpc
      protocol: TCP
      port: 14269
      targetPort: 14269
  type: ClusterIP