apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-frontend
  namespace: social-network
  labels:
    app: media-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-frontend
  template:
    metadata:
      labels:
        app: media-frontend
    spec:
      initContainers:
        - name: copy-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /usr/local/openresty/nginx/lua-scripts /usr/local/openresty/nginx/conf;
              cp -r /lua-scripts/* /usr/local/openresty/nginx/lua-scripts/;
              cp -r /nginx-config/* /usr/local/openresty/nginx/conf/
          volumeMounts:
            - name: media-frontend-lua-scripts-volume
              mountPath: /lua-scripts
            - name: media-frontend-nginx-config-volume
              mountPath: /nginx-config
      containers:
        - name: media-frontend
          image: yg397/media-frontend:xenial
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: media-frontend-lua-scripts-volume
          configMap:
            name: media-frontend-lua-scripts
        - name: media-frontend-nginx-config-volume
          configMap:
            name: media-frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: media-frontend
  namespace: social-network
spec:
  selector:
    app: media-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort