apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
  namespace: social-network
  labels:
    app: nginx-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-server
  template:
    metadata:
      labels:
        app: nginx-web-server
    spec:
      containers:
        - name: nginx-web-server
          image: yg397/openresty-thrift:xenial
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: lua-scripts-volume
              mountPath: /usr/local/openresty/nginx/lua-scripts
            - name: pages-volume
              mountPath: /usr/local/openresty/nginx/pages
            - name: nginx-conf-volume
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: jaeger-config-volume
              mountPath: /usr/local/openresty/nginx/jaeger-config.json
              subPath: jaeger-config.json
            - name: gen-lua-volume
              mountPath: /gen-lua
            - name: lua-thrift-volume
              mountPath: /usr/local/openresty/lualib/thrift
            - name: keys-volume
              mountPath: /keys
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: lua-scripts-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/nginx-web-server/lua-scripts

        - name: pages-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/nginx-web-server/pages

        - name: nginx-conf-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/nginx-web-server/conf/nginx.conf

        - name: jaeger-config-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/nginx-web-server/jaeger-config.json

        - name: gen-lua-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/gen-lua

        - name: lua-thrift-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/docker/openresty-thrift/lua-thrift

        - name: keys-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/keys
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-server
  namespace: social-network
spec:
  selector:
    app: nginx-web-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort