apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-service
  namespace: social-network
  labels:
    app: post-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-storage-service
  template:
    metadata:
      labels:
        app: post-storage-service
    spec:
      containers:
        - name: post-storage-service
          image: localhost:5000/social-network-microservices:withLog_01
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          command: ["PostStorageService"]
          volumeMounts:
            - name: config-volume
              mountPath: /social-network-microservices/config
            - name: tls-volume
              mountPath: /keys
      volumes:
        - name: config-volume
          configMap:
            name: service-config
        - name: tls-volume
          secret:
            secretName: tls
---
apiVersion: v1
kind: Service
metadata:
  name: post-storage-service
  namespace: social-network
spec:
  selector:
    app: post-storage-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP