apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-redis
  namespace: social-network
  labels:
    app: social-graph-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-graph-redis
  template:
    metadata:
      labels:
        app: social-graph-redis
    spec:
      containers:
        - name: redis
          image: redis
          command: ["redis-server", "/social-network-microservices/config/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-volume
              mountPath: /social-network-microservices/config
            - name: keys-volume
              mountPath: /keys
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: config-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/config

        - name: keys-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/keys
---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
  namespace: social-network
spec:
  selector:
    app: social-graph-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP