apiVersion: apps/v1
kind: Deployment
metadata:
  name: unique-id-service
  namespace: social-network
  labels:
    app: unique-id-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unique-id-service
  template:
    metadata:
      labels:
        app: unique-id-service
    spec:
      containers:
        - name: unique-id-service
          image: node-0:5000/social-network-microservices:withLog_01
          command: ["UniqueIdService"]
          volumeMounts:
            - name: config-volume
              mountPath: /social-network-microservices/config
            - name: keys-volume
              mountPath: /keys
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: config-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/config

        - name: keys-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/keys
---
apiVersion: v1
kind: Service
metadata:
  name: unique-id-service
  namespace: social-network
spec:
  selector:
    app: unique-id-service
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP