apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-memcached
  namespace: social-network
  labels:
    app: url-shorten-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shorten-memcached
  template:
    metadata:
      labels:
        app: url-shorten-memcached
    spec:
      containers:
        - name: memcached
          image: memcached
          args:
            - "-m"
            - "16384"
            - "-t"
            - "8"
            - "-I"
            - "32m"
            - "-c"
            - "4096"
          ports:
            - containerPort: 11211
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-memcached
  namespace: social-network
spec:
  selector:
    app: url-shorten-memcached
  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: 11211
  type: ClusterIP