apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-mongodb
  namespace: social-network
  labels:
    app: url-shorten-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shorten-mongodb
  template:
    metadata:
      labels:
        app: url-shorten-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          command: ["mongod", "--nojournal", "--quiet", "--config", "/social-network-microservices/config/mongod.conf"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: config-volume
              mountPath: /social-network-microservices/config
            - name: keys-volume
              mountPath: /keys
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"

      volumes:
        - name: config-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/config

        - name: keys-volume
          hostPath:
            path: /users/pianwan/DeathStarBench/socialNetwork/keys
---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-mongodb
  namespace: social-network
spec:
  selector:
    app: url-shorten-mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP